language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed elkouranjica/udagram-api-feed:latest
  - docker tag udagram-api-user elkouranjica/udagram-api-user:latest
  - docker tag udagram-frontend elkouranjica/udagram-frontend:latest
  - docker tag udagram-reverseproxy elkouranjica/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elkouranjica/udagram-api-feed:latest
  - docker push elkouranjica/udagram-api-user:latest
  - docker push elkouranjica/udagram-frontend:latest
  - docker push elkouranjica/udagram-reverseproxy:latest

